// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ContactList: typeof import('./components/home/contactList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeRight: typeof import('./components/home/HomeRight.vue')['default']
    IEpPromotion: typeof import('~icons/ep/promotion')['default']
    ImageForm: typeof import('./components/home/dialogForm/imageForm.vue')['default']
    IndexBody: typeof import('./components/index/indexBody.vue')['default']
    IndexHeader: typeof import('./components/index/indexHeader.vue')['default']
    LoginForm: typeof import('./components/login/loginForm.vue')['default']
    MenuRight: typeof import('./components/home/menuRight.vue')['default']
    Register: typeof import('./components/login/register.vue')['default']
    RegisterForm: typeof import('./components/login/registerForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TBackTop: typeof import('tdesign-vue-next')['BackTop']
    TBadge: typeof import('tdesign-vue-next')['Badge']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TCol: typeof import('tdesign-vue-next')['Col']
    TComment: typeof import('tdesign-vue-next')['Comment']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    THeader: typeof import('tdesign-vue-next')['Header']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TList: typeof import('tdesign-vue-next')['List']
    TListItem: typeof import('tdesign-vue-next')['ListItem']
    TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta']
    TMenu: typeof import('tdesign-vue-next')['Menu']
    TMenuGroup: typeof import('tdesign-vue-next')['MenuGroup']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TRow: typeof import('tdesign-vue-next')['Row']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
    TUpload: typeof import('tdesign-vue-next')['Upload']
    UserMsg: typeof import('./components/home/userMsg.vue')['default']
  }
}
