// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    Form: typeof import('./components/login/form.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IEpPromotion: typeof import('~icons/ep/promotion')['default']
    IndexBody: typeof import('./components/index/indexBody.vue')['default']
    IndexHeader: typeof import('./components/index/indexHeader.vue')['default']
    LoginForm: typeof import('./components/login/loginForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCol: typeof import('tdesign-vue-next')['Col']
    THeadMenu: typeof import('tdesign-vue-next')['HeadMenu']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TMenuItem: typeof import('tdesign-vue-next')['MenuItem']
    TRow: typeof import('tdesign-vue-next')['Row']
  }
}
